import type { ChatTurnRequest, ChatTurnResponse, CompletionRequest, CompletionResponse } from '@minicode/shared';
import type { ModelAdapter } from './providers.js';
import { summarizeProjectIndex } from './projectIndex.js';
import { suggestToolCalls } from './tools.js';

export class AgentRuntime {
  constructor(private readonly adapter: ModelAdapter) {}

  async runChat(request: ChatTurnRequest): Promise<ChatTurnResponse> {
    const projectIndexSummary = request.context.projectIndexSummary || summarizeProjectIndex(request.cwd);
    const enrichedRequest: ChatTurnRequest = {
      ...request,
      context: {
        ...request.context,
        projectIndexSummary
      }
    };

    const toolCalls = suggestToolCalls(request.mode, request.prompt);
    const completion = await this.adapter.completeChat(enrichedRequest);
    const summary = projectIndexSummary
      ? `Consulted project index. ${projectIndexSummary}`
      : 'No project index was available.';

    return {
      sessionId: request.sessionId,
      mode: request.mode,
      message: completion,
      toolCalls,
      summary
    };
  }

  async runCompletion(request: CompletionRequest): Promise<CompletionResponse> {
    const suggestions = await this.adapter.completeInline(request);
    return {
      items: suggestions
        .filter((text) => text.length > 0)
        .map((text) => ({
          text,
          detail: `Generated by ${this.adapter.id}`
        }))
    };
  }
}
